### ISSUE TITLE
[Bug] Undiagnosed parse error

### ISSUE THREAD

**Issue by elpekenin** [elpekenin/circuitpython_toml#5]
Reported on [Discord](<https://discord.com/channels/327254708534116352/537365702651150357/1226101231399735306>)

```toml
[entry]
bg = "waves"
text = "Hello World"
options = [ ["(T)est", "card"] ]
```
Causes
```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "_toml.py", line 349, in load
  File "_toml.py", line 343, in loads
  File "_toml.py", line 170, in __init__
  File "_toml.py", line 298, in _parse_line
TOMLError: Malformed string, check out your quotes in line 4
```

**Comment by elpekenin** [comment]
Solved by 681197f7d2b3774f7d13513d8b7c4aeadbd89ad7
